#!/usr/bin/env python3
"""Applies voice sticky-indicator and sidebar cosmetics edits to chat-ui.js."""
import os
import shutil
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
filepath = os.path.join(ROOT, "chat-git-main", "client", "public", "modules", "chat-ui.js")

backup = filepath + ".bak"
shutil.copy2(filepath, backup)
with open(filepath, "r", encoding="utf-8") as f:
    content = f.read()

def apply(src, old, new, label):
    n = src.count(old)
    if not n:
        print(f"!! MISS  {label}: anchor not found", file=sys.stderr)
        return src, 0
    if n > 1:
        print(f"!! MULTI {label}: anchor matched {n} times", file=sys.stderr)
        return src, 0
    print(f"OK  apply {label}")
    return src.replace(old, new, 1), 1

# ============================================================
# VOICE: sticky/latching indicator for local and remote speakers
# ============================================================

OLD_REMOTE = (
"  const setRemoteSpeakingState = (participantName, isSpeaking) => {\n"
"    const normalizedName = String(participantName || '').trim();\n"
"    if (!normalizedName) return;\n"
"    state.voiceRemoteSpeaking.set(normalizedName, !!isSpeaking);\n"
"    updateVoiceCallParticipants(state.voiceCallParticipants);\n"
"  };"
)
NEW_REMOTE = (
"  // Sticky/latching remote-speaking indicator: turn ON instantly when a peer\n"
"  // reports speaking, but only flip OFF after sustained silence (~250ms) so\n"
"  // brief pauses between words/syllables don't strobe the indicator off and on.\n"
"  const REMOTE_SPEAKING_OFF_DELAY_MS = 250;\n"
"  const remoteVoiceSpeakingOffTimers = new Map();\n"
"\n"
"  const flushRemoteSpeakingTimers = () => {\n"
"    remoteVoiceSpeakingOffTimers.forEach((timer) => clearTimeout(timer));\n"
"    remoteVoiceSpeakingOffTimers.clear();\n"
"  };\n"
"\n"
"  const setRemoteSpeakingState = (participantName, isSpeaking) => {\n"
"    const normalizedName = String(participantName || '').trim();\n"
"    if (!normalizedName) return;\n"
"    if (isSpeaking) {\n"
"      if (remoteVoiceSpeakingOffTimers.has(normalizedName)) {\n"
"        clearTimeout(remoteVoiceSpeakingOffTimers.get(normalizedName));\n"
"        remoteVoiceSpeakingOffTimers.delete(normalizedName);\n"
"      }\n"
"      if (!state.voiceRemoteSpeaking.get(normalizedName)) {\n"
"        state.voiceRemoteSpeaking.set(normalizedName, true);\n"
"        updateVoiceCallParticipants(state.voiceCallParticipants);\n"
"      }\n"
"    } else {\n"
"      if (remoteVoiceSpeakingOffTimers.has(normalizedName)) {\n"
"        clearTimeout(remoteVoiceSpeakingOffTimers.get(normalizedName));\n"
"      }\n"
"      remoteVoiceSpeakingOffTimers.set(normalizedName, setTimeout(() => {\n"
"        state.voiceRemoteSpeaking.set(normalizedName, false);\n"
"        remoteVoiceSpeakingOffTimers.delete(normalizedName);\n"
"        updateVoiceCallParticipants(state.voiceCallParticipants);\n"
"      }, REMOTE_SPEAKING_OFF_DELAY_MS));\n"
"    }\n"
"  };"
)
content, _ = apply(content, OLD_REMOTE, NEW_REMOTE, "voice:remote-hysteresis")

OLD_START = (
"  const startSpeakingDetection = async () => {\n"
"    try {\n"
"      if (state.audioContext) return; // Already started\n"
"\n"
"      state.audioContext = new (window.AudioContext || window.webkitAudioContext)();\n"
"      state.analyser = state.audioContext.createAnalyser();\n"
"      state.analyser.fftSize = 256;\n"
"\n"
"      const bufferLength = state.analyser.frequencyBinCount;\n"
"      const dataArray = new Uint8Array(bufferLength);\n"
"\n"
"      const checkAudioLevel = () => {\n"
"        if (!state.analyser) {\n"
"          setSpeakingState(false);\n"
"          return;\n"
"        }\n"
"\n"
"        if (state.isMicMuted) {\n"
"          setSpeakingState(false);\n"
"          requestAnimationFrame(checkAudioLevel);\n"
"          return;\n"
"        }\n"
"\n"
"        state.analyser.getByteFrequencyData(dataArray);\n"
"\n"
"        // Calculate average volume\n"
"        let sum = 0;\n"
"        for (let i = 0; i < bufferLength; i++) {\n"
"          sum += dataArray[i];\n"
"        }\n"
"        const average = sum / bufferLength;\n"
"\n"
"        // Threshold for speaking detection (adjust as needed)\n"
"        const isSpeaking = average > 15;\n"
"        setSpeakingState(isSpeaking);\n"
"\n"
"        requestAnimationFrame(checkAudioLevel);\n"
"      };\n"
"\n"
"      checkAudioLevel();\n"
"\n"
"    } catch (error) {\n"
"      console.error('Error starting speaking detection:', error);\n"
"    }\n"
"  };\n"
"\n"
"  const stopSpeakingDetection = () => {\n"
"    if (state.audioContext) {\n"
"      state.audioContext.close();\n"
"      state.audioContext = null;\n"
"      state.analyser = null;\n"
"    }\n"
"    setSpeakingState(false);\n"
"  };"
)
NEW_START = (
"  // Sticky/latching local-speaking indicator: turn ON instantly when the mic\n"
"  // crosses a loudness threshold, and only flip OFF after sustained silence\n"
"  // (~250ms). This keeps the \"talking\" indicator steady while the user is\n"
"  // actually speaking instead of strobing for every short sound.\n"
"  const SPEAKING_THRESHOLD = 15;\n"
"  const SPEAKING_MIN_OFF_DELAY_MS = 250;\n"
"  let localSpeakingLastLoudAt = 0;\n"
"\n"
"  const startSpeakingDetection = async () => {\n"
"    try {\n"
"      if (state.audioContext) return; // Already started\n"
"\n"
"      state.audioContext = new (window.AudioContext || window.webkitAudioContext)();\n"
"      state.analyser = state.audioContext.createAnalyser();\n"
"      state.analyser.fftSize = 256;\n"
"\n"
"      const bufferLength = state.analyser.frequencyBinCount;\n"
"      const dataArray = new Uint8Array(bufferLength);\n"
"\n"
"      const checkAudioLevel = () => {\n"
"        if (!state.analyser) {\n"
"          localSpeakingLastLoudAt = 0;\n"
"          setSpeakingState(false);\n"
"          return;\n"
"        }\n"
"\n"
"        if (state.isMicMuted) {\n"
"          localSpeakingLastLoudAt = 0;\n"
"          if (state.isSpeaking) setSpeakingState(false);\n"
"          requestAnimationFrame(checkAudioLevel);\n"
"          return;\n"
"        }\n"
"\n"
"        state.analyser.getByteFrequencyData(dataArray);\n"
"\n"
"        // Calculate average volume\n"
"        let sum = 0;\n"
"        for (let i = 0; i < bufferLength; i++) {\n"
"          sum += dataArray[i];\n"
"        }\n"
"        const average = sum / bufferLength;\n"
"\n"
"        const now = (typeof performance !== 'undefined' && performance.now)\n"
"          ? performance.now()\n"
"          : Date.now();\n"
"\n"
"        // Sticky speaking: ON instantly when loud, ON through short pauses\n"
"        // between words, OFF only after sustained silence (~250ms).\n"
"        if (average > SPEAKING_THRESHOLD) {\n"
"          localSpeakingLastLoudAt = now;\n"
"          if (!state.isSpeaking) setSpeakingState(true);\n"
"        } else if (state.isSpeaking) {\n"
"          if (now - localSpeakingLastLoudAt >= SPEAKING_MIN_OFF_DELAY_MS) {\n"
"            localSpeakingLastLoudAt = 0;\n"
"            setSpeakingState(false);\n"
"          }\n"
"        }\n"
"\n"
"        requestAnimationFrame(checkAudioLevel);\n"
"      };\n"
"\n"
"      checkAudioLevel();\n"
"\n"
"    } catch (error) {\n"
"      console.error('Error starting speaking detection:', error);\n"
"    }\n"
"  };\n"
"\n"
"  const stopSpeakingDetection = () => {\n"
"    if (state.audioContext) {\n"
"      state.audioContext.close();\n"
"      state.audioContext = null;\n"
"      state.analyser = null;\n"
"    }\n"
"    localSpeakingLastLoudAt = 0;\n"
"    setSpeakingState(false);\n"
"  };"
)
content, _ = apply(content, OLD_START, NEW_START, "voice:local-hysteresis")

OLD_HIDE = (
"    // Stop speaking detection\n"
"    stopSpeakingDetection();\n"
"\n"
"    // Stop voice streaming\n"
"    stopVoiceStreaming();\n"
"\n"
"    // Stop microphone stream\n"
"    if (state.microphoneStream) {\n"
"      state.microphoneStream.getTracks().forEach(track => track.stop());\n"
"      state.microphoneStream = null;\n"
"    }\n"
"  };"
)
NEW_HIDE = (
"    // Stop speaking detection\n"
"    stopSpeakingDetection();\n"
"    flushRemoteSpeakingTimers();\n"
"\n"
"    // Stop voice streaming\n"
"    stopVoiceStreaming();\n"
"\n"
"    // Stop microphone stream\n"
"    if (state.microphoneStream) {\n"
"      state.microphoneStream.getTracks().forEach(track => track.stop());\n"
"      state.microphoneStream = null;\n"
"    }\n"
"  };"
)
content, _ = apply(content, OLD_HIDE, NEW_HIDE, "voice:hide-panel-flush")

# ============================================================
# COSMETICS SIDEBAR: collapsible banners + chat tags picker
# ============================================================

OLD_LAYOUT = (
"            <div id=\"sidebar-channels\" class=\"sidebar-section-list sidebar-channels-list\"></div>\n"
"          </div>"
)
NEW_LAYOUT = (
"            <div id=\"sidebar-channels\" class=\"sidebar-section-list sidebar-channels-list\"></div>\n"
"          </div>\n"
"          <div class=\"sidebar-section sidebar-cosmetics-section\">\n"
"            <div class=\"sidebar-section-header sidebar-cosmetics-toggle\" id=\"sidebar-cosmetics-header\" role=\"button\" tabindex=\"0\" aria-expanded=\"false\">\n"
"              <span class=\"sidebar-section-label\">Cosmetics</span>\n"
"              <span id=\"sidebar-cosmetics-chevron\" class=\"section-chevron\">&#9656;</span>\n"
"            </div>\n"
"            <div id=\"sidebar-cosmetics\" class=\"sidebar-section-list sidebar-cosmetics-list hidden\"></div>\n"
"          </div>"
)
content, _ = apply(content, OLD_LAYOUT, NEW_LAYOUT, "sidebar:cosmetics-html")

OLD_RENDER_HEADER = (
"  const renderSidebar = () => {\n"
"    const dmRoot = document.getElementById('sidebar-direct-messages');"
)
NEW_RENDER_HEADER = (
"  // Cosmetic catalog (banners + chat tags) comes from the same fallbackEffects\n"
"  // list shipped to the storefront settings page so names, prices and\n"
"  // descriptions line up with the catalog without an extra API call.\n"
"  const COSMETIC_CATALOG = (Array.isArray(fallbackEffects) ? fallbackEffects : [])\n"
"    .filter((entry) => entry && (entry.scope === 'banner' || entry.scope === 'tag'));\n"
"\n"
"  const COSMETIC_STYLES_TEXT = `\n"
"    .sidebar-cosmetics-toggle { cursor: pointer; user-select: none; }\n"
"    .sidebar-cosmetics-toggle:hover { background: rgba(255,255,255,0.04); }\n"
"    .section-chevron {\n"
"      margin-left: auto;\n"
"      padding-right: 4px;\n"
"      font-size: 10px;\n"
"      color: var(--text-3);\n"
"      transition: transform 180ms ease;\n"
"      display: inline-block;\n"
"    }\n"
"    .sidebar-cosmetics-toggle[aria-expanded=\"true\"] .section-chevron {\n"
"      transform: rotate(90deg);\n"
"    }\n"
"    .sidebar-cosmetics-list {\n"
"      padding: 6px 8px 10px 8px;\n"
"      display: flex;\n"
"      flex-direction: column;\n"
"      gap: 10px;\n"
"    }\n"
"    .cosmetic-category-label {\n"
"      font-size: 10px;\n"
"      text-transform: uppercase;\n"
"      letter-spacing: 0.08em;\n"
"      color: var(--text-3);\n"
"      font-weight: 700;\n"
"      padding: 2px 4px 4px;\n"
"    }\n"
"    .cosmetic-row {\n"
"      display: flex;\n"
"      align-items: center;\n"
"      gap: 8px;\n"
"      padding: 6px 8px;\n"
"      border: 1px solid var(--border);\n"
"      border-radius: 8px;\n"
"      background: var(--bg-raised, rgba(255,255,255,0.04));\n"
"      transition: background 120ms ease, border-color 120ms ease;\n"
"      cursor: pointer;\n"
"    }\n"
"    .cosmetic-row:hover {\n"
"      background: rgba(255,255,255,0.06);\n"
"      border-color: rgba(255,255,255,0.12);\n"
"    }\n"
"    .cosmetic-row.equipped {\n"
"      border-color: var(--accent, #6366f1);\n"
"      background: rgba(99,102,241,0.14);\n"
"    }\n"
"    .cosmetic-row.locked { opacity: 0.78; }\n"
"    .cosmetic-preview {\n"
"      width: 24px;\n"
"      height: 24px;\n"
"      border-radius: 6px;\n"
"      flex-shrink: 0;\n"
"      background: var(--bg, #1f1f24);\n"
"      border: 1px solid var(--border);\n"
"      display: flex;\n"
"      align-items: center;\n"
"      justify-content: center;\n"
"      font-size: 10px;\n"
"      font-weight: 700;\n"
"      color: var(--text-3);\n"
"      overflow: hidden;\n"
"    }\n"
"    .cosmetic-info {\n"
"      flex: 1;\n"
"      min-width: 0;\n"
"      display: flex;\n"
"      flex-direction: column;\n"
"      gap: 2px;\n"
"    }\n"
"    .cosmetic-name {\n"
"      font-size: 12px;\n"
"      font-weight: 600;\n"
"      color: var(--text-1);\n"
"      white-space: nowrap;\n"
"      overflow: hidden;\n"
"      text-overflow: ellipsis;\n"
"    }\n"
"    .cosmetic-meta {\n"
"      font-size: 10px;\n"
"      color: var(--text-3);\n"
"      font-family: var(--font-mono, monospace);\n"
"    }\n"
"    .cosmetic-btn {\n"
"      flex-shrink: 0;\n"
"      font-size: 10px;\n"
"      font-weight: 700;\n"
"      letter-spacing: 0.04em;\n"
"      text-transform: uppercase;\n"
"      padding: 4px 8px;\n"
"      border-radius: 6px;\n"
"      border: 1px solid var(--border-md, rgba(255,255,255,0.18));\n"
"      background: var(--bg, #1f1f24);\n"
"      color: var(--text-1);\n"
"      cursor: pointer;\n"
"    }\n"
"    .cosmetic-btn:disabled { opacity: 0.45; cursor: not-allowed; }\n"
"    .cosmetic-btn.equip-action {\n"
"      background: var(--accent, #6366f1);\n"
"      border-color: var(--accent, #6366f1);\n"
"      color: #fff;\n"
"    }\n"
"    .cosmetic-row.equipped .cosmetic-btn.equip-action {\n"
"      background: rgba(99,102,241,0.18);\n"
"      color: var(--text-1);\n"
"      border-color: var(--accent, #6366f1);\n"
"    }\n"
"    .cosmetic-btn.buy-action {\n"
"      background: rgba(245,197,66,0.16);\n"
"      border-color: rgba(245,197,66,0.55);\n"
"      color: #f5c542;\n"
"    }\n"
"  `;\n"
"  let cosmeticsStyleInjected = false;\n"
"  const injectCosmeticsStyles = () => {\n"
"    if (cosmeticsStyleInjected) return;\n"
"    cosmeticsStyleInjected = true;\n"
"    try {\n"
"      const styleEl = document.createElement('style');\n"
"      styleEl.setAttribute('data-tlk-cosmetics', '1');\n"
"      styleEl.textContent = COSMETIC_STYLES_TEXT;\n"
"      document.head.appendChild(styleEl);\n"
"    } catch {}\n"
"  };\n"
"\n"
"  const getCosmeticsState = () => {\n"
"    const user = state.user || {};\n"
"    const defaultBanner = ['none'];\n"
"    const defaultTag = ['none'];\n"
"    const ownedBanners = Array.isArray(user.ownedBanners) && user.ownedBanners.length\n"
"      ? user.ownedBanners\n"
"      : (user.equippedBanner && user.equippedBanner !== 'none' && !user.ownedBanners\n"
"          ? [user.equippedBanner, 'none']\n"
"          : defaultBanner);\n"
"    const ownedTags = Array.isArray(user.ownedTags) && user.ownedTags.length\n"
"      ? user.ownedTags\n"
"      : (user.equippedTag && user.equippedTag !== 'none' && !user.ownedTags\n"
"          ? [user.equippedTag, 'none']\n"
"          : defaultTag);\n"
"    return {\n"
"      ownedBanners,\n"
"      equippedBanner: String(user.equippedBanner || 'none').trim().toLowerCase() || 'none',\n"
"      ownedTags,\n"
"      equippedTag: String(user.equippedTag || 'none').trim().toLowerCase() || 'none',\n"
"      coins: Math.max(0, Number(user.coins || 0))\n"
"    };\n"
"  };\n"
"\n"
"  const cosmeticEndpoint = (kind, action, id) => {\n"
"    if (kind === 'banner') {\n"
"      return action === 'buy'\n"
"        ? `/api/tlk/chat-banners/${encodeURIComponent(id)}/purchase`\n"
"        : '/api/tlk/chat-banners/equip';\n"
"    }\n"
"    return action === 'buy'\n"
"      ? `/api/tlk/chat-tags/${encodeURIComponent(id)}/purchase`\n"
"      : '/api/tlk/chat-tags/equip';\n"
"  };\n"
"\n"
"  const renderCosmeticRow = (entry, kind, equipped, ownedSet, coins) => {\n"
"    const id = String(entry && entry.id || '').trim().toLowerCase();\n"
"    const name = esc(String((entry && entry.name) || entry && entry.id || 'Item'));\n"
"    const price = Math.max(0, Math.round(Number(entry && entry.price || 0) * 100) / 100);\n"
"    const isEquipped = equipped === id;\n"
"    const owned = ownedSet.indexOf(id) !== -1;\n"
"    const canAfford = coins >= price;\n"
"    const previewLetter = (String((entry && entry.name) || entry && entry.id || '?').trim().charAt(0) || '?').toUpperCase();\n"
"    const previewTint = kind === 'banner'\n"
"      ? 'linear-gradient(135deg, #4f46e5 0%, #ec4899 100%)'\n"
"      : 'linear-gradient(135deg, #06b6d4 0%, #facc15 100%)';\n"
"    const action = id === 'none' ? 'equip' : (owned ? 'equip' : 'buy');\n"
"    let btnLabel;\n"
"    if (isEquipped) btnLabel = 'Equipped';\n"
"    else if (id === 'none') btnLabel = 'Clear';\n"
"    else if (owned) btnLabel = 'Equip';\n"
"    else if (canAfford) btnLabel = `Buy ${formatCoins(price)}c`;\n"
"    else btnLabel = `Need ${formatCoins(price)}c`;\n"
"    const btnClass = `cosmetic-btn ${isEquipped ? 'equip-action' : action + '-action'}`;\n"
"    const disabled = id !== 'none' && !isEquipped && !owned && !canAfford;\n"
"    return `\n"
"      <div class=\"cosmetic-row ${isEquipped ? 'equipped' : ''} ${owned ? '' : 'locked'}\" data-cosmetic-id=\"${esc(id)}\" data-cosmetic-kind=\"${esc(kind)}\" data-cosmetic-action=\"${esc(action)}\">\n"
"        <div class=\"cosmetic-preview\" style=\"background:${previewTint};color:#fff;\">${esc(previewLetter)}</div>\n"
"        <div class=\"cosmetic-info\">\n"
"          <div class=\"cosmetic-name\">${name}</div>\n"
"          <div class=\"cosmetic-meta\">${owned ? (isEquipped ? 'Equipped' : 'Owned') : esc(`Price · ${formatCoins(price)} coin${price === 1 ? '' : 's'}`)}</div>\n"
"        </div>\n"
"        <button type=\"button\" class=\"${btnClass}\" data-cosmetic-button=\"1\" ${disabled ? 'disabled' : ''}>${esc(btnLabel)}</button>\n"
"      </div>\n"
"    `;\n"
"  };\n"
"\n"
"  const renderCosmeticsPanel = () => {\n"
"    injectCosmeticsStyles();\n"
"    const root = document.getElementById('sidebar-cosmetics');\n"
"    const header = document.getElementById('sidebar-cosmetics-header');\n"
"    const chevron = document.getElementById('sidebar-cosmetics-chevron');\n"
"    if (!root || !header) return;\n"
"\n"
"    const bannerEntries = [{ id: 'none', name: 'No banner', price: 0, scope: 'banner' }]\n"
"      .concat(COSMETIC_CATALOG.filter((entry) => entry.scope === 'banner'));\n"
"    const tagEntries = [{ id: 'none', name: 'No chat tag', price: 0, scope: 'tag' }]\n"
"      .concat(COSMETIC_CATALOG.filter((entry) => entry.scope === 'tag'));\n"
"\n"
"    let storedOpen = '0';\n"
"    try { storedOpen = String(localStorage.getItem('tlkCosmeticsPanelOpen') || '0'); } catch { storedOpen = '0'; }\n"
"    const isOpen = storedOpen === '1';\n"
"    root.classList.toggle('hidden', !isOpen);\n"
"    header.setAttribute('aria-expanded', isOpen ? 'true' : 'false');\n"
"    if (chevron) chevron.textContent = isOpen ? '\\u25bc' : '\\u25b6';\n"
"\n"
"    const state0 = getCosmeticsState();\n"
"    const bannerHtml = bannerEntries\n"
"      .map((entry) => renderCosmeticRow(entry, 'banner', state0.equippedBanner, state0.ownedBanners, state0.coins))\n"
"      .join('');\n"
"    const tagHtml = tagEntries\n"
"      .map((entry) => renderCosmeticRow(entry, 'tag', state0.equippedTag, state0.ownedTags, state0.coins))\n"
"      .join('');\n"
"\n"
"    root.innerHTML = `\n"
"      <div class=\"cosmetic-category-label\">Banners</div>\n"
"      ${bannerHtml}\n"
"      <div class=\"cosmetic-category-label\">Chat tags</div>\n"
"      ${tagHtml}\n"
"    `;\n"
"\n"
"    if (!header._cosmeticsToggleBound) {\n"
"      header._cosmeticsToggleBound = true;\n"
"      const toggle = () => {\n"
"        const opened = root.classList.contains('hidden');\n"
"        root.classList.toggle('hidden', !opened);\n"
"        header.setAttribute('aria-expanded', opened ? 'true' : 'false');\n"
"        if (chevron) chevron.textContent = opened ? '\\u25bc' : '\\u25b6';\n"
"        try { localStorage.setItem('tlkCosmeticsPanelOpen', opened ? '1' : '0'); } catch {}\n"
"      };\n"
"      header.addEventListener('click', toggle);\n"
"      header.addEventListener('keydown', (event) => {\n"
"        if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); toggle(); }\n"
"      });\n"
"    }\n"
"\n"
"    if (!root._cosmeticsActionBound) {\n"
"      root._cosmeticsActionBound = true;\n"
"      root.addEventListener('click', async (event) => {\n"
"        const row = event.target.closest('.cosmetic-row');\n"
"        if (!row) return;\n"
"        event.stopPropagation();\n"
"        const id = String(row.getAttribute('data-cosmetic-id') || '').trim().toLowerCase();\n"
"        const kind = String(row.getAttribute('data-cosmetic-kind') || '').trim();\n"
"        if (!id || !kind) return;\n"
"        const action = id === 'none' ? 'equip' : (row.getAttribute('data-cosmetic-action') || 'equip');\n"
"        const buttonEl = row.querySelector('.cosmetic-btn');\n"
"        if (buttonEl && buttonEl.disabled) return;\n"
"        if (buttonEl) { buttonEl.disabled = true; buttonEl.textContent = action === 'buy' ? 'Buying...' : 'Equipping...'; }\n"
"        try {\n"
"          const endpoint = cosmeticEndpoint(kind, action, id);\n"
"          const payload = action === 'buy' ? undefined : { [`${kind}Id`]: id };\n"
"          const data = await api(endpoint, { method: 'POST', body: payload });\n"
"          if (data && data.user) applyUserSnapshot(data.user);\n"
"          renderCosmeticsPanel();\n"
"          const label = kind === 'banner' ? 'Banner' : 'Tag';\n"
"          showToast((data && data.msg) || (action === 'buy' ? `${label} unlocked` : `${label} equipped`), 'success');\n"
"        } catch (err) {\n"
"          showToast((err && err.message) || 'Could not update cosmetic', 'error');\n"
"          renderCosmeticsPanel();\n"
"        }\n"
"      });\n"
"    }\n"
"  };\n"
"\n"
"  const renderSidebar = () => {\n"
"    renderCosmeticsPanel();\n"
"    const dmRoot = document.getElementById('sidebar-direct-messages');"
)
content, _ = apply(content, OLD_RENDER_HEADER, NEW_RENDER_HEADER, "renderSidebar:cosmetics-helpers")

OLD_CHANNELS_END = (
"    channelRoot.querySelectorAll('[data-channel-id]').forEach((el) => {\n"
"      el.addEventListener('click', () => navigate(`/channels/${el.getAttribute('data-channel-id')}`));\n"
"    });\n"
"\n"
"    void subscribeToMessageRooms();"
)
NEW_CHANNELS_END = (
"    channelRoot.querySelectorAll('[data-channel-id]').forEach((el) => {\n"
"      el.addEventListener('click', () => navigate(`/channels/${el.getAttribute('data-channel-id')}`));\n"
"    });\n"
"\n"
"    void subscribeToMessageRooms();\n"
"    renderCosmeticsPanel();"
)
content, _ = apply(content, OLD_CHANNELS_END, NEW_CHANNELS_END, "renderSidebar:refresh-cosmetics")

with open(filepath, "w", encoding="utf-8") as f:
    f.write(content)

print(f"DONE: {filepath}")
print(f"Backup: {backup}")
